version: '3.8'
services:
  python_env:
    build: .
    volumes:
      - .:/app
    stdin_open: true  # Keep STDIN open
    tty: true        # Allocate a pseudo-TTY
    env_file: .env
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'    # Limit to 2 CPU cores
        reservations:
          memory: 1G   # Guarantee at least 1GB of memory
